# Databricks notebook source

# MAGIC %md
# MAGIC # Lab 01 SOLUTION: Genie Code Fundamentals
# MAGIC **For facilitator use — share with participants after the lab.**

# COMMAND ----------

# MAGIC %md
# MAGIC ## Setup (same as lab)

# COMMAND ----------

from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType,
    TimestampType, IntegerType, DateType
)
from pyspark.sql import functions as F
import datetime, random

spark = SparkSession.builder.getOrCreate()

schema = StructType([
    StructField("nmi",             StringType(),   False),
    StructField("interval_date",   DateType(),     False),
    StructField("interval_number", IntegerType(),  False),
    StructField("read_kwh",        DoubleType(),   True),
    StructField("quality_flag",    StringType(),   True),
    StructField("meter_serial",    StringType(),   True),
    StructField("region",          StringType(),   True),
])

random.seed(42)
rows = []
base = datetime.date(2024, 7, 1)
nmis = ["6001234567", "6009876543"]
regions = {"6001234567": "NSW1", "6009876543": "VIC1"}

for nmi in nmis:
    for day_offset in range(7):
        d = base + datetime.timedelta(days=day_offset)
        for interval in range(1, 49):
            hour = (interval - 1) / 2.0
            base_load = 0.8 if nmi == "6001234567" else 1.2
            peak_factor = 2.5 if 7 <= hour <= 9 or 17 <= hour <= 20 else 1.0
            noise = random.gauss(0, 0.05)
            kwh = max(0.0, round(base_load * peak_factor + noise, 3))
            quality = "A" if random.random() > 0.05 else "E"
            rows.append((nmi, d, interval, kwh, quality, f"METER-{nmi[-4:]}", regions[nmi]))

df_meters = spark.createDataFrame(rows, schema=schema)
df_meters.createOrReplaceTempView("nem12_interval_reads")
print(f"Created nem12_interval_reads with {df_meters.count():,} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 2.1 SOLUTION — Daily consumption per NMI

# COMMAND ----------

# SOLUTION: Generated by Genie Code (or written manually as reference)
df_daily = (
    spark.sql("""
        SELECT
            nmi,
            region,
            interval_date,
            ROUND(SUM(read_kwh), 3) AS total_kwh
        FROM nem12_interval_reads
        GROUP BY nmi, region, interval_date
        ORDER BY nmi, interval_date
    """)
)

df_daily.show(14, truncate=False)
# Expected: 14 rows (2 NMIs × 7 days)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 2.2 SOLUTION — Peak interval per NMI per day (actual reads)

# COMMAND ----------

from pyspark.sql.window import Window

window_spec = Window.partitionBy("nmi", "interval_date").orderBy(F.col("read_kwh").desc())

df_peak = (
    df_meters
    .filter(F.col("quality_flag") == "A")
    .withColumn("rank", F.rank().over(window_spec))
    .filter(F.col("rank") == 1)
    .select(
        "nmi",
        "interval_date",
        F.col("interval_number").alias("peak_interval_number"),
        F.col("read_kwh").alias("peak_kwh"),
    )
    .orderBy("nmi", "interval_date")
)

df_peak.show(14, truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 4.1 SOLUTION — Fix column name error

# COMMAND ----------

# FIXED: quality_flg → quality_flag
df_bug1_fixed = (
    df_meters
    .filter(F.col("quality_flag") == "A")          # FIXED
    .groupBy("nmi", "region")
    .agg(F.sum("read_kwh").alias("total_kwh"))
)
df_bug1_fixed.show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 4.2 SOLUTION — Fix logic error (> 0.05, not < 0.05)

# COMMAND ----------

# FIXED: changed < 0.05 to > 0.05
df_bug2_fixed = (
    df_meters
    .groupBy("nmi")
    .agg(
        F.count("*").alias("total_intervals"),
        F.sum(F.when(F.col("quality_flag") == "E", 1).otherwise(0)).alias("estimated_count")
    )
    .withColumn("pct_estimated", F.col("estimated_count") / F.col("total_intervals"))
    .filter(F.col("pct_estimated") > 0.05)   # FIXED
)
df_bug2_fixed.show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 4.3 SOLUTION — Fix format typo

# COMMAND ----------

output_path = "/tmp/nem12_daily_output"

# FIXED: "dleta" → "delta"
(
    df_meters
    .groupBy("nmi", "interval_date")
    .agg(F.sum("read_kwh").alias("total_kwh"))
    .write
    .format("delta")          # FIXED
    .mode("overwrite")
    .save(output_path)
)
print(f"Written to {output_path}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 5.1 SOLUTION — Documented function

# COMMAND ----------

def calculate_load_factor(peak_kwh: float, total_kwh: float, periods: int = 48) -> float:
    """Calculate the load factor for a NEM meter over a given period.

    The load factor measures how consistently a meter's energy consumption is spread
    across all intervals. A load factor of 1.0 means perfectly flat consumption;
    values closer to 0 indicate high peak-to-average ratio (peaky demand).

    In the NEM, load factor is used by network operators to assess demand diversity
    and by retailers to profile customer consumption behaviour.

    Args:
        peak_kwh: The maximum single-interval energy read in kWh.
        total_kwh: The total energy consumed across all intervals in kWh.
        periods: Number of intervals in the analysis period (default 48 = one day).

    Returns:
        Load factor as a float between 0.0 and 1.0, rounded to 4 decimal places.
        Returns 0.0 if peak_kwh is zero or negative.
    """
    if peak_kwh <= 0:
        return 0.0
    average_kwh = total_kwh / periods
    return round(average_kwh / peak_kwh, 4)


lf = calculate_load_factor(peak_kwh=2.8, total_kwh=68.4, periods=48)
print(f"Load factor: {lf}")
# Expected: ~0.5089

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 5.2 SOLUTION — Optimised transformation (Spark-native)

# COMMAND ----------

# OPTIMISED: replaced Python loop with Spark filter + collect only the count
df_flagged = (
    df_meters
    .filter(F.col("nmi") == "6001234567")
    .filter(F.col("read_kwh") > 2.0)
    .select("nmi", "interval_date", "interval_number", "read_kwh")
)

count = df_flagged.count()
print(f"High-consumption intervals: {count}")
df_flagged.show(3, truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 7.1 SOLUTION — 7-day rolling average

# COMMAND ----------

from pyspark.sql.window import Window

# Daily totals first
df_daily_totals = (
    df_meters
    .groupBy("nmi", "interval_date")
    .agg(F.sum("read_kwh").alias("daily_kwh"))
)

# Rolling 7-day window ordered by date
window_7d = (
    Window.partitionBy("nmi")
    .orderBy(F.col("interval_date").cast("long"))
    .rowsBetween(-6, 0)          # current row + 6 previous rows = 7 days
)

df_rolling = (
    df_daily_totals
    .withColumn("rolling_7d_avg_kwh", F.round(F.avg("daily_kwh").over(window_7d), 3))
    .orderBy("nmi", "interval_date")
)

df_rolling.show(14, truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 7.2 SOLUTION — Flag missing intervals

# COMMAND ----------

from pyspark.sql.window import Window

def flag_missing_intervals(df, nmi_col: str = "nmi", date_col: str = "interval_date", interval_col: str = "interval_number"):
    """Flag rows where the interval_number jumps by more than 1 within an NMI+date group.

    A gap greater than 1 between consecutive interval numbers indicates a missing
    30-minute interval in the NEM12 file — a data quality issue that must be resolved
    before submitting to AEMO.

    Args:
        df: PySpark DataFrame containing interval reads.
        nmi_col: Column name for the NMI identifier.
        date_col: Column name for the date.
        interval_col: Column name for the interval number.

    Returns:
        DataFrame filtered to only rows where a gap exists before this interval.
        Includes a 'gap_size' column showing the size of the jump.
    """
    window_spec = (
        Window.partitionBy(nmi_col, date_col)
        .orderBy(interval_col)
    )

    return (
        df
        .withColumn("prev_interval", F.lag(interval_col, 1).over(window_spec))
        .withColumn("gap_size", F.col(interval_col) - F.col("prev_interval"))
        .filter(F.col("gap_size") > 1)
        .select(nmi_col, date_col, "prev_interval", interval_col, "gap_size")
    )


gaps = flag_missing_intervals(df_meters)
gap_count = gaps.count()
print(f"Missing interval gaps found: {gap_count}")
if gap_count > 0:
    gaps.show()
else:
    print("No missing intervals — all 48 intervals per NMI per day are present.")
