# Databricks notebook source

# MAGIC %md
# MAGIC # Lab 02 SOLUTION: Notebook AI Features & Chat
# MAGIC **For facilitator use — share with participants after the lab.**

# COMMAND ----------

# MAGIC %md
# MAGIC ## Setup (same as lab — run this first)

# COMMAND ----------

CATALOG = "main"
SCHEMA  = "workshop_lab"

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")

from pyspark.sql.types import *
from pyspark.sql import functions as F
import datetime, random

spark.sql(f"""
CREATE OR REPLACE TABLE {CATALOG}.{SCHEMA}.meter_register (
    nmi              STRING  COMMENT 'National Meter Identifier — unique per connection point',
    customer_id      STRING  COMMENT 'Internal customer account reference',
    tariff_code      STRING  COMMENT 'Network tariff classification (e.g. TOU, FLAT)',
    meter_type       STRING  COMMENT 'Type: SMART (interval) or BASIC (accumulation)',
    install_date     DATE    COMMENT 'Date the meter was commissioned at this address',
    last_read_date   DATE    COMMENT 'Most recent successful meter read date',
    region           STRING  COMMENT 'NEM region: NSW1, VIC1, QLD1, SA1, TAS1',
    status           STRING  COMMENT 'ACTIVE | RETIRED | DISPUTED'
)
COMMENT 'NEM meter register — one row per connection point'
""")

spark.sql(f"""
CREATE OR REPLACE TABLE {CATALOG}.{SCHEMA}.interval_reads (
    nmi              STRING    COMMENT 'National Meter Identifier',
    read_date        DATE      COMMENT 'Calendar date of the reading',
    interval_number  INT       COMMENT '30-minute interval number within the day (1=00:00–00:30, 48=23:30–24:00)',
    read_kwh         DOUBLE    COMMENT 'Energy consumed in the interval, kilowatt-hours',
    quality_flag     STRING    COMMENT 'A=Actual, E=Estimated, S=Substituted',
    created_at       TIMESTAMP COMMENT 'When this record was loaded into the platform'
)
COMMENT 'NEM12 interval meter reads — 30-minute granularity'
PARTITIONED BY (read_date)
""")

spark.sql(f"""
CREATE OR REPLACE TABLE {CATALOG}.{SCHEMA}.asset_maintenance (
    asset_id                 STRING  COMMENT 'Unique asset identifier (transformer, line, switch)',
    asset_type               STRING  COMMENT 'TRANSFORMER | SWITCH | CABLE | METER',
    work_order_id            STRING  COMMENT 'SAP work order reference',
    maintenance_date         DATE    COMMENT 'Date maintenance was performed',
    technician_id            STRING  COMMENT 'Staff ID of the technician',
    work_type                STRING  COMMENT 'PREVENTIVE | CORRECTIVE | EMERGENCY',
    outage_duration_minutes  INT     COMMENT 'Planned or actual customer outage in minutes (0 if none)',
    affected_nmis            INT     COMMENT 'Number of customer connections affected',
    cost_aud                 DOUBLE  COMMENT 'Total cost of work order in AUD',
    notes                    STRING  COMMENT 'Free-text technician notes'
)
COMMENT 'Asset maintenance work orders — regulatory reporting source for SAIDI/SAIFI'
""")

spark.sql(f"""
CREATE OR REPLACE TABLE {CATALOG}.{SCHEMA}.regulatory_thresholds (
    threshold_id    STRING COMMENT 'Unique threshold rule ID',
    region          STRING COMMENT 'NEM region this rule applies to',
    threshold_type  STRING COMMENT 'SAIDI | SAIFI | VOLTAGE | FREQUENCY',
    limit_value     DOUBLE COMMENT 'Regulatory limit value',
    unit            STRING COMMENT 'Unit: minutes/year, outages/year, V, Hz',
    effective_from  DATE   COMMENT 'Date from which this threshold is enforceable',
    regulator       STRING COMMENT 'Regulator: AER | AEMO | ESC | QCA'
)
COMMENT 'Regulatory performance thresholds by region — sourced from AER determinations'
""")

print("Tables ready.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 2.3 SOLUTION — Join interval_reads to meter_register

# COMMAND ----------

# SQL join generated by the Assistant (example — your Assistant may vary slightly)
result = spark.sql(f"""
    SELECT
        ir.nmi,
        mr.region,
        mr.tariff_code,
        ir.read_date,
        ir.interval_number,
        ir.read_kwh,
        ir.quality_flag
    FROM {CATALOG}.{SCHEMA}.interval_reads ir
    INNER JOIN {CATALOG}.{SCHEMA}.meter_register mr
        ON ir.nmi = mr.nmi
    ORDER BY ir.nmi, ir.read_date, ir.interval_number
""")

print(f"Query executed successfully. Rows: {result.count()} (0 expected — no data loaded yet)")
result.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 3.1 SOLUTION — Daily reliability report

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC     region,
# MAGIC     maintenance_date,
# MAGIC     SUM(outage_duration_minutes)                          AS total_outage_minutes,
# MAGIC     SUM(affected_nmis)                                    AS total_affected_nmis,
# MAGIC     COUNT(CASE WHEN work_type = 'EMERGENCY'   THEN 1 END) AS emergency_work_orders,
# MAGIC     COUNT(CASE WHEN work_type = 'PREVENTIVE'  THEN 1 END) AS preventive_work_orders
# MAGIC FROM main.workshop_lab.asset_maintenance
# MAGIC GROUP BY region, maintenance_date
# MAGIC ORDER BY region, maintenance_date

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 3.2 SOLUTION — Regulatory threshold breach check

# COMMAND ----------

# MAGIC %sql
# MAGIC -- SAIDI breach check: actual vs AER threshold per region
# MAGIC WITH saidi_actual AS (
# MAGIC     SELECT
# MAGIC         asset_id,
# MAGIC         -- In a real scenario, asset_maintenance would have a region column
# MAGIC         -- Using a placeholder join here — adapt to your schema
# MAGIC         SUM(outage_duration_minutes) AS actual_saidi_minutes,
# MAGIC         COUNT(*)                     AS work_order_count
# MAGIC     FROM main.workshop_lab.asset_maintenance
# MAGIC     WHERE YEAR(maintenance_date) = YEAR(CURRENT_DATE())
# MAGIC     GROUP BY asset_id
# MAGIC ),
# MAGIC thresholds AS (
# MAGIC     SELECT region, limit_value AS limit_minutes
# MAGIC     FROM main.workshop_lab.regulatory_thresholds
# MAGIC     WHERE threshold_type = 'SAIDI'
# MAGIC )
# MAGIC SELECT
# MAGIC     a.asset_id,
# MAGIC     a.actual_saidi_minutes,
# MAGIC     t.limit_minutes,
# MAGIC     (a.actual_saidi_minutes > t.limit_minutes)   AS breach,
# MAGIC     a.work_order_count                           AS contributing_work_orders
# MAGIC FROM saidi_actual a
# MAGIC -- Cross join to first threshold as a proxy (adapt region join to your schema)
# MAGIC CROSS JOIN (SELECT limit_minutes FROM thresholds LIMIT 1) t
# MAGIC WHERE a.actual_saidi_minutes > t.limit_minutes

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 7.1 SOLUTION — Full pipeline

# COMMAND ----------

# Load sample data first (adapts from Lab 03 seed data)
import datetime, random
from pyspark.sql.types import *

random.seed(1)
ir_rows = []
for day_offset in range(30):
    d = datetime.date.today() - datetime.timedelta(days=day_offset)
    for interval in range(1, 49):
        ir_rows.append((
            "6001234567", d, interval,
            round(random.uniform(0.3, 2.5), 3),
            "A",
            datetime.datetime.now(),
        ))

ir_schema = StructType([
    StructField("nmi",             StringType(),    False),
    StructField("read_date",       DateType(),      False),
    StructField("interval_number", IntegerType(),   False),
    StructField("read_kwh",        DoubleType(),    True),
    StructField("quality_flag",    StringType(),    True),
    StructField("created_at",      TimestampType(), True),
])

spark.createDataFrame(ir_rows, ir_schema) \
    .write.format("delta").mode("overwrite").option("overwriteSchema", "true") \
    .saveAsTable(f"{CATALOG}.{SCHEMA}.interval_reads")

mr_rows = [("6001234567", "CUST-001", "TOU", "SMART",
            datetime.date(2020, 1, 1), datetime.date.today(), "NSW1", "ACTIVE")]
mr_schema = StructType([
    StructField("nmi",           StringType(), False),
    StructField("customer_id",   StringType(), True),
    StructField("tariff_code",   StringType(), True),
    StructField("meter_type",    StringType(), True),
    StructField("install_date",  DateType(),   True),
    StructField("last_read_date",DateType(),   True),
    StructField("region",        StringType(), True),
    StructField("status",        StringType(), True),
])
spark.createDataFrame(mr_rows, mr_schema) \
    .write.format("delta").mode("overwrite").option("overwriteSchema", "true") \
    .saveAsTable(f"{CATALOG}.{SCHEMA}.meter_register")

print("Sample data loaded for pipeline exercise.")

# COMMAND ----------

# Full pipeline: last 30 days consumption per NMI, joined to meter_register
from datetime import date, timedelta

cutoff = date.today() - timedelta(days=30)

df_pipeline = (
    spark.table(f"{CATALOG}.{SCHEMA}.interval_reads")
    .filter(F.col("read_date") >= cutoff)
    .groupBy("nmi")
    .agg(F.round(F.sum("read_kwh"), 3).alias("total_kwh_30d"))
    .join(
        spark.table(f"{CATALOG}.{SCHEMA}.meter_register").select("nmi", "region", "tariff_code"),
        on="nmi",
        how="inner",
    )
    .select("nmi", "region", "tariff_code", "total_kwh_30d")
)

# Write result
(
    df_pipeline
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(f"{CATALOG}.{SCHEMA}.monthly_consumption_summary")
)

print("Pipeline complete.")
spark.table(f"{CATALOG}.{SCHEMA}.monthly_consumption_summary").show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Exercise 7.2 SOLUTION — Fix the join key error

# COMMAND ----------

# FIXED: join key changed from "meter_id" to "nmi"
df_fixed = (
    spark.table(f"{CATALOG}.{SCHEMA}.interval_reads")
    .join(
        spark.table(f"{CATALOG}.{SCHEMA}.meter_register"),
        on="nmi",        # FIXED: was "meter_id"
        how="inner",
    )
    .select("nmi", "region", "read_date", "read_kwh")
)
df_fixed.show(5)
